###
#PRIMERO DEBES GUARDAR TODO EL ARRAY DE PRODUCTOS
#TOCA SEND PARA QUE TE TRAIGA EL ARRAY Y DESPUES DELAJO 
#DOS LINEAS ABAJO DE Content-Type
GET  http://localhost:3000/api/test/backupProduct
###


###
#DESPUES QUE HAYAS BORRADO LA BASE DE DATOS, SIEMBRALA NUEVAMENTE
#TOCANDO EL SEND, FELIZ BACKUP HAHA
POST http://localhost:3000/api/test/sembradoJSON
Content-Type: application/json

[
  {
    "name": "CHURROS WITH CHOCOLATE SAUCE",
    "image": [
      "[{\"id\":1,\"image\":\"https://izzycooking.com/wp-content/uploads/2021/05/Churros-683x1024.jpg\"},{\"id\":1,\"image\":\"https://www.pequerecetas.com/wp-content/uploads/2010/05/chocolate-con-churros-receta.jpg\"},{\"id\":1,\"image\":\"https://www.pequerecetas.com/wp-content/uploads/2010/05/chocolate-con-churros-receta.jpg\"}]"
    ],
    "price": 300,
    "dimension": 13,
    "category": "desserts",
    "type": "none",
    "description": "This easy and delicious dessert can be made at home using a few ingredients from the pantry",
    "available": true
  },
  {
    "name": "Bakery",
    "image": [
      "[{\"id\":1,\"image\":\"https://www.mashed.com/img/gallery/the-best-bakery-in-every-state/intro-1601499029.jpg\"},{\"id\":1,\"image\":\"https://www.syntegon.com/hubfs/bakery-packaging-technology.jpg\"},{\"id\":1,\"image\":\"https://www.syntegon.com/hubfs/bakery-packaging-technology.jpg\"}]"
    ],
    "price": 800,
    "dimension": 28,
    "category": "bakery",
    "type": "none",
    "description": "Pack for 12, ideal with coffee",
    "available": true
  },
  {
    "name": "Ricotta and Red Fruits",
    "image": [
      "[{\"id\":1,\"image\":\"https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5401.jpg\"},{\"id\":1,\"image\":\"https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5397.jpg\"},{\"id\":1,\"image\":\"https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5404.jpg\"}]"
    ],
    "price": 999,
    "dimension": 22,
    "category": "cakes",
    "type": "celiac",
    "description": "I recommend consuming at room temperature.",
    "available": true
  },
  {
    "name": "AUTUMN MERINGUE CAKE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689\"}]"
    ],
    "price": 1000,
    "dimension": 12,
    "category": "cakes",
    "type": "celiac",
    "description": "Crispy almond-shaped Merringue discs capable of field delicacy and cream. Decorated around with our caramelized nougat.",
    "available": true
  },
  {
    "name": "Black forest",
    "image": [
      "[{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"},{\"id\":1,\"image\":\"https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg\"},{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"}]"
    ],
    "price": 9054,
    "dimension": 24,
    "category": "cakes",
    "type": "vegan",
    "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
    "available": true
  },
  {
    "name": "Apple Pie American Recipe",
    "image": [
      "[{\"id\":1,\"image\":\"https://elcomercio.pe/resizer/ch7RZSXSwBhGNtdfW1lNgetFF4E=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/THZFW43X3RFG3AQ7EKOCHBPSQU.jpg\"},{\"id\":1,\"image\":\"https://cdn7.kiwilimon.com/recetaimagen/35454/42532.jpg\"},{\"id\":1,\"image\":\"https://cdn7.kiwilimon.com/recetaimagen/35454/42532.jpg\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cakes",
    "type": "vegan",
    "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
    "available": true
  },
  {
    "name": "THOUSAND LEAVES CALUGA AND MANJAR",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas1_600x.jpg?v=1617044711\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas2_600x.jpg?v=1617044712\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas2_600x.jpg?v=1617044712\"}]"
    ],
    "price": 10000,
    "dimension": 80,
    "category": "cakes",
    "type": "vegan",
    "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
    "available": true
  },
  {
    "name": "Fun Cookies",
    "image": [
      "[{\"id\":1,\"image\":\"https://i2.wp.com/smittenkitchen.com/wp-content/uploads//2016/05/confetti-cookies1.jpg?fit=1200%2C800&ssl=1\"},{\"id\":1,\"image\":\"https://celebratingsweets.com/wp-content/uploads/2013/08/Sprinkle-Cookies-3.jpg\"},{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKoYx_qLSlpGbvVlcXwWVkE0VjyKLrkLqjRw&usqp=CAU\"}]"
    ],
    "price": 900,
    "dimension": 5,
    "category": "cookies",
    "type": "vegan",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "Pepa cookies",
    "image": [
      "[{\"id\":1,\"image\":\"https://img-global.cpcdn.com/recipes/18fa4a17da40b644/400x400cq70/photo.jpg\"},{\"id\":1,\"image\":\"https://img-global.cpcdn.com/recipes/18fa4a17da40b644/400x400cq70/photo.jpg\"},{\"id\":1,\"image\":\"https://www.petitchef.es/imgupl/recipe/galletas-pepas--md-17877p22242.jpg\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cookies",
    "type": "vegan",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "TRES LECHES CAKE",
    "image": [
      "[{\"id\":1,\"image\":\"https://izzycooking.com/wp-content/uploads/2021/05/Tres-Leches-Cake-683x1024.jpg\"},{\"id\":1,\"image\":\"https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg\"},{\"id\":1,\"image\":\"https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg\"}]"
    ],
    "price": 500,
    "dimension": 3,
    "category": "desserts",
    "type": "none",
    "description": "This easy and delicious dessert can be made at home using a few ingredients from the pantry",
    "available": true
  },
  {
    "name": "Chocolate cupcake",
    "image": [
      "[{\"id\":1,\"image\":\"https://cuk-it.com/wp-content/uploads/2021/04/thumb04-1-e1617910758384.jpg\"},{\"id\":1,\"image\":\"https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2020/04/muffin-de-chocolate-tipo-costco.jpg\"},{\"id\":1,\"image\":\"https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2020/04/muffin-de-chocolate-tipo-costco.jpg\"}]"
    ],
    "price": 800,
    "dimension": 28,
    "category": "muffins",
    "type": "none",
    "description": "Ideal for mid-afternoon",
    "available": true
  },
  {
    "name": "THOUSAND SHEETS CALUGA LOVE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-carlugaamor1_600x.jpg?v=1617044677\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugaamor2_600x.jpg?v=1617044677\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-carlugaamor1_600x.jpg?v=1617044677\"}]"
    ],
    "price": 7780,
    "dimension": 5,
    "category": "cakes",
    "type": "vegan_celiac",
    "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
    "available": true
  },
  {
    "name": "RASPBERRY CHEESECAKE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa1_600x.jpg?v=1617045234\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa2_600x.jpg?v=1617045234\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa2_600x.jpg?v=1617045234\"}]"
    ],
    "price": 770,
    "dimension": 50,
    "category": "cakes",
    "type": "celiac",
    "description": "Raspberry New York Cheesecake",
    "available": true
  },
  {
    "name": "Oreo Sweet Milk",
    "image": [
      "[{\"id\":1,\"image\":\"https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20200216_1334161-d81750f3c456e8aa9f15818709253532-640-0.jpg\"},{\"id\":1,\"image\":\"https://www.recetasderechupete.com/wp-content/uploads/2019/11/Tarta-de-Oreo.jpg\"},{\"id\":1,\"image\":\"https://www.recetasderechupete.com/wp-content/uploads/2019/11/Tarta-de-Oreo.jpg\"}]"
    ],
    "price": 750,
    "dimension": 10,
    "category": "cakes",
    "type": "none",
    "description": "Oreo Dulce de leche cake. Diameter 22 cm. Approximate weight 2,750 kg. Surrender approx 20-25 People. Ideal to eat chilled or frozen.",
    "available": true
  },
  {
    "name": "INDIVIDUAL DESSERTS LEMON PIE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/postre-piedelimon_600x.jpg?v=1617045101\"},{\"id\":1,\"image\":\"https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg\"},{\"id\":1,\"image\":\"https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg\"}]"
    ],
    "price": 520,
    "dimension": 2,
    "category": "others",
    "type": "none",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "Black forest",
    "image": [
      "[{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"},{\"id\":1,\"image\":\"https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg\"},{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cakes",
    "type": "vegan",
    "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
    "available": true
  },
  {
    "name": "Black forest",
    "image": [
      "[{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"},{\"id\":1,\"image\":\"https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg\"},{\"id\":1,\"image\":\"https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cakes",
    "type": "vegan",
    "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
    "available": true
  },
  {
    "name": "Chocolate Cookies",
    "image": [
      "[{\"id\":1,\"image\":\"https://recetasdecocina.elmundo.es/wp-content/uploads/2015/09/cookies-receta.jpg\"},{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0UA3HyIV8R_jYrw4_fyBb4p-iY81OCde9nw&usqp=CAU\"},{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGcQGY3CHADrs5dMlhtr0dtdmz968Fd-8BzQ&usqp=CAU\"}]"
    ],
    "price": 650,
    "dimension": 5,
    "category": "cookies",
    "type": "celiac",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "SPANISH SPONGE CAKE",
    "image": [
      "[{\"id\":1,\"image\":\"https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg\"},{\"id\":1,\"image\":\"https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg\"},{\"id\":1,\"image\":\"https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg\"}]"
    ],
    "price": 500,
    "dimension": 3,
    "category": "desserts",
    "type": "none",
    "description": "This classic recipe uses four basic ingredients. The lemon zest adds an extra touch of flavor.",
    "available": true
  },
  {
    "name": "Banana muffin",
    "image": [
      "[{\"id\":1,\"image\":\"https://www.cucinare.tv/wp-content/uploads/2020/04/Dise%C3%B1o-sin-t%C3%ADtulo-2020-04-01T174207.157.png\"},{\"id\":1,\"image\":\"https://www.cucinare.tv/wp-content/uploads/2020/04/Dise%C3%B1o-sin-t%C3%ADtulo-2020-04-01T174207.157.png\"},{\"id\":1,\"image\":\"https://gastronomiaycia.republica.com/wp-content/photos/muffins_platano1.jpg\"}]"
    ],
    "price": 500,
    "dimension": 22,
    "category": "muffins",
    "type": "none",
    "description": "Ideal for morning",
    "available": true
  },
  {
    "name": "RASPBERRY APPLE CRUMBLE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana1_600x.jpg?v=1617045510\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana2_600x.jpg?v=1617045510\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana1_600x.jpg?v=1617045510\"}]"
    ],
    "price": 10000,
    "dimension": 20,
    "category": "cakes",
    "type": "none",
    "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
    "available": true
  },
  {
    "name": "CRÈME BRÛLÉE",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto2_600x.png?v=1638218786\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto_600x.png?v=1638218786\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto_600x.png?v=1638218786\"}]"
    ],
    "price": 600,
    "dimension": 32,
    "category": "cakes",
    "type": "vegan",
    "description": "Cake based on sponge cake filled with brigadeiro de Crème brûlée.",
    "available": true
  },
  {
    "name": "Classic Brownie",
    "image": [
      "[{\"id\":1,\"image\":\"https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180731_1134311-b2bbffb442411a79da15818622543447-640-0.jpg\"},{\"id\":1,\"image\":\"https://resizer.glanacion.com/resizer/pBj8lKhdrfhPsyFOokrN9_ojafA=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/3RCML7355NGQTODJ7WC6Q2WZWA.jpg\"},{\"id\":1,\"image\":\"https://resizer.glanacion.com/resizer/pBj8lKhdrfhPsyFOokrN9_ojafA=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/3RCML7355NGQTODJ7WC6Q2WZWA.jpg\"}]"
    ],
    "price": 280,
    "dimension": 2,
    "category": "cakes",
    "type": "none",
    "description": "Brownie cake with walnuts, natural dulce de leche and Italian meringue, decorated with chocolate threads. Diameter 22 cm, estimated weight 2.6 kg.",
    "available": true
  },
  {
    "name": "BOX AREA-BARS AND BISCUITS",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones2_600x.jpg?v=1642189325\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones2_600x.jpg?v=1642189325\"},{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones3_1_600x.jpg?v=1642189325\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "bakery",
    "type": "none",
    "description": "This box contains our variety of artisan cookies and bars designed to share.",
    "available": true
  },
  {
    "name": "Black forest",
    "image": [
      "[{\"id\":1,\"image\":\"https://cdn.shopify.com/s/files/1/0422/0069/4951/products/postre-piedelimon_600x.jpg?v=1617045101\"},{\"id\":1,\"image\":\"https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg\"},{\"id\":1,\"image\":\"https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cakes",
    "type": "vegan",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "Black Cookies",
    "image": [
      "[{\"id\":1,\"image\":\"https://simplelivingrecipes.com/wp-content/uploads/2022/03/fudgy-chocolate-cookies-with-cocoa-powder-s.jpg\"},{\"id\":1,\"image\":\"https://i.blogs.es/80c2c8/galletas-cookies-chocolate/840_560.jpg\"},{\"id\":1,\"image\":\"https://www.sweetestmenu.com/wp-content/uploads/2020/04/chocolatecookies12a.jpg\"}]"
    ],
    "price": 700,
    "dimension": 5,
    "category": "cookies",
    "type": "none",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "Christmas Cookies",
    "image": [
      "[{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqVifX15AZWfFgAS7Hg_fj-QAibbEHPzeqPQ&usqp=CAU\"},{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrkJEGDMg4jlQlf0EQ2tnoYBtp9OgGZ_BFiQ&usqp=CAU\"},{\"id\":1,\"image\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx2ymJuZUpDSh58mTcN7GLiW4bnb0IscC6_M2m0wSq4POtY_IkbT5x5v5sriSk9i0UPEQ&usqp=CAU\"}]"
    ],
    "price": 7780,
    "dimension": 30,
    "category": "cookies",
    "type": "vegan_celiac",
    "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
    "available": true
  },
  {
    "name": "Muffins de frutilla",
    "image": [
      "[{\"id\":\"qkccuad9chwsezp8omti\",\"image\":\"https://res.cloudinary.com/dqhbskhe7/image/upload/v1668686110/prueba_eze/qkccuad9chwsezp8omti.jpg\"},{\"id\":\"t5bolace6lyq8a6vmt6h\",\"image\":\"https://res.cloudinary.com/dqhbskhe7/image/upload/v1668686114/prueba_eze/t5bolace6lyq8a6vmt6h.jpg\"},{\"id\":\"faoyn79oyspnc1icnhhz\",\"image\":\"https://res.cloudinary.com/dqhbskhe7/image/upload/v1668686116/prueba_eze/faoyn79oyspnc1icnhhz.jpg\"},{\"id\":\"omtaxu0igyhxeg6mnzsk\",\"image\":\"https://res.cloudinary.com/dqhbskhe7/image/upload/v1668686119/prueba_eze/omtaxu0igyhxeg6mnzsk.jpg\"}]"
    ],
    "price": 1000,
    "dimension": 30,
    "category": "muffins",
    "type": "vegan",
    "description": "Incluye 6",
    "available": true
  }
]
###


