
### ////////// others muffins cookies bakery  desserts cakes bakery
##             Otras magdalenas galletas panadería postres pasteles panadería

POST http://localhost:3000/api/test/sembradoAux
Content-Type: application/json

[
    
 {
        "name": "SPANISH SPONGE CAKE",
        "price": 500,
        "dimension": 3,
        "available": true,
        "type": "none",
        "category": "desserts",
        "image": [
            {
               
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg"
            },
            { 
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg"
            },
            {
                "image": "https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg"
            }
        ],
        "description": "This classic recipe uses four basic ingredients. The lemon zest adds an extra touch of flavor.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "TRES LECHES CAKE",
        "price": 500,
        "dimension": 3,
        "available": true,
        "type": "none",
        "category": "desserts",
        "image": [
            {
               
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Tres-Leches-Cake-683x1024.jpg"
            },
            {
               
                "image": "https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg"
            },
            {
               
                "image": "https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg"
            }
        ],
        "description": "This easy and delicious dessert can be made at home using a few ingredients from the pantry",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "CHURROS WITH CHOCOLATE SAUCE",
        "price": 300,
        "dimension": 13,
        "available": true,
        "type": "none",
        "category": "desserts",
        "image": [
            {
               
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Churros-683x1024.jpg"
            },
            {
               
                "image": "https://www.pequerecetas.com/wp-content/uploads/2010/05/chocolate-con-churros-receta.jpg"
            },
            {
               
                "image": "https://www.pequerecetas.com/wp-content/uploads/2010/05/chocolate-con-churros-receta.jpg"
            }
        ],
        "description": "This easy and delicious dessert can be made at home using a few ingredients from the pantry",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Bakery",
        "price": 800,
        "dimension": 28,
        "available": true,
        "type": "none",
        "category": "bakery",
        "image": [
            {
               
                "image": "https://www.mashed.com/img/gallery/the-best-bakery-in-every-state/intro-1601499029.jpg"
            },
            {
               
                "image": "https://www.syntegon.com/hubfs/bakery-packaging-technology.jpg"
            },
            {
               
                "image": "https://www.syntegon.com/hubfs/bakery-packaging-technology.jpg"
            }
        ],
        "description": "Pack for 12, ideal with coffee",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Banana muffin",
        "price": 500,
        "dimension": 22,
        "available": true,
        "type": "none",
        "category": "muffins",
        "image": [
            {
               
                "image": "https://www.cucinare.tv/wp-content/uploads/2020/04/Dise%C3%B1o-sin-t%C3%ADtulo-2020-04-01T174207.157.png"
            },
            {
               
                "image": "https://www.cucinare.tv/wp-content/uploads/2020/04/Dise%C3%B1o-sin-t%C3%ADtulo-2020-04-01T174207.157.png"
            },
            {
               
                "image": "https://gastronomiaycia.republica.com/wp-content/photos/muffins_platano1.jpg"
            }
        ],
        "description": "Ideal for morning",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Ricotta and Red Fruits",
        "price": 999,
        "dimension": 22,
        "available": true,
        "type": "celiac",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5401.jpg"
            },
            {
               
                "image": "https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5397.jpg"
            },
            {
               
                "image": "https://esruiz.com.ar/tienda/wp-content/uploads/2018/07/ricotayfrutosrojos_img_5404.jpg"
            }
        ],
        "description": "I recommend consuming at room temperature.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "THOUSAND SHEETS CALUGA LOVE",
        "price": 7780,
        "dimension": 5,
        "available": true,
        "type": "vegan_celiac",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-carlugaamor1_600x.jpg?v=1617044677"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugaamor2_600x.jpg?v=1617044677"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-carlugaamor1_600x.jpg?v=1617044677"
            }
        ],
        "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "RASPBERRY APPLE CRUMBLE",
        "price": 10000,
        "dimension": 20,
        "available": true,
        "type": "none",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana1_600x.jpg?v=1617045510"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana2_600x.jpg?v=1617045510"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/crumble-frambuesamanzana1_600x.jpg?v=1617045510"
            }
        ],
        "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "CHOCOLATE CAKE",
        "price": 100,
        "dimension": 40,
        "available": true,
        "type": "none",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-chocolate1_600x.jpg?v=1617044908"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-chocolate2_600x.jpg?v=1617044908"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-chocolate1_600x.jpg?v=1617044908"
            }
        ],
        "description": "Chocolate cake filled with manjar blanco.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "RASPBERRY CHEESECAKE",
        "price": 770,
        "dimension": 50,
        "available": true,
        "type": "celiac",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa1_600x.jpg?v=1617045234"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa2_600x.jpg?v=1617045234"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/cheesecake-frambuesa2_600x.jpg?v=1617045234"
            }
        ],
        "description": "Raspberry New York Cheesecake",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "CRÈME BRÛLÉE",
        "price": 600,
        "dimension": 32,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto2_600x.png?v=1638218786"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto_600x.png?v=1638218786"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/producto_600x.png?v=1638218786"
            }
        ],
        "description": "Cake based on sponge cake filled with brigadeiro de Crème brûlée.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "THOUSAND LEAVES CALUGA AND MANJAR",
        "price": 10000,
        "dimension": 80,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas1_600x.jpg?v=1617044711"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas2_600x.jpg?v=1617044712"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/torta-calugamilhojas2_600x.jpg?v=1617044712"
            }
        ],
        "description": "Thousand leaf cake with homemade caluga, cream, white delicacy and touches of raspberry",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "AUTUMN MERINGUE CAKE",
        "price": 1000,
        "dimension": 12,
        "available": true,
        "type": "celiac",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/1000X1000_LANZAMIENTO_Mesa_de_trabajo_1_copia_3_600x.jpg?v=1662648689"
            }
        ],
        "description": "Crispy almond-shaped Merringue discs capable of field delicacy and cream. Decorated around with our caramelized nougat.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Oreo Sweet Milk",
        "price": 750,
        "dimension": 10,
        "available": true,
        "type": "none",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20200216_1334161-d81750f3c456e8aa9f15818709253532-640-0.jpg"
            },
            {
               
                "image": "https://www.recetasderechupete.com/wp-content/uploads/2019/11/Tarta-de-Oreo.jpg"
            },
            {
               
                "image": "https://www.recetasderechupete.com/wp-content/uploads/2019/11/Tarta-de-Oreo.jpg"
            }
        ],
        "description": "Oreo Dulce de leche cake. Diameter 22 cm. Approximate weight 2,750 kg. Surrender approx 20-25 People. Ideal to eat chilled or frozen.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Classic Brownie",
        "price": 280,
        "dimension": 2,
        "available": true,
        "type": "none",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180731_1134311-b2bbffb442411a79da15818622543447-640-0.jpg"
            },
            {
               
                "image": "https://resizer.glanacion.com/resizer/pBj8lKhdrfhPsyFOokrN9_ojafA=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/3RCML7355NGQTODJ7WC6Q2WZWA.jpg"
            },
            {
               
                "image": "https://resizer.glanacion.com/resizer/pBj8lKhdrfhPsyFOokrN9_ojafA=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/3RCML7355NGQTODJ7WC6Q2WZWA.jpg"
            }
        ],
        "description": "Brownie cake with walnuts, natural dulce de leche and Italian meringue, decorated with chocolate threads. Diameter 22 cm, estimated weight 2.6 kg.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Black forest",
        "price": 9054,
        "dimension": 24,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            },
            {
               
                "image": "https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg"
            },
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            }
        ],
        "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "INDIVIDUAL DESSERTS LEMON PIE",
        "price": 520,
        "dimension": 2,
        "available": true,
        "type": "none",
        "category": "others",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/postre-piedelimon_600x.jpg?v=1617045101"
            },
            {
               
                "image": "https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg"
            },
            {
               
                "image": "https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "BOX AREA-BARS AND BISCUITS",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "none",
        "category": "bakery",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones2_600x.jpg?v=1642189325"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones2_600x.jpg?v=1642189325"
            },
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/AREABOX-barrasygalletones3_1_600x.jpg?v=1642189325"
            }
        ],
        "description": "This box contains our variety of artisan cookies and bars designed to share.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Apple Pie American Recipe",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://elcomercio.pe/resizer/ch7RZSXSwBhGNtdfW1lNgetFF4E=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/THZFW43X3RFG3AQ7EKOCHBPSQU.jpg"
            },
            {
               
                "image": "https://cdn7.kiwilimon.com/recetaimagen/35454/42532.jpg"
            },
            {
               
                "image": "https://cdn7.kiwilimon.com/recetaimagen/35454/42532.jpg"
            }
        ],
        "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Black forest",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            },
            {
               
                "image": "https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg"
            },
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            }
        ],
        "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Black forest",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://cdn.shopify.com/s/files/1/0422/0069/4951/products/postre-piedelimon_600x.jpg?v=1617045101"
            },
            {
               
                "image": "https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg"
            },
            {
               
                "image": "https://annaspasteleria.com/wp-content/uploads/2016/06/30-1438-post/DSC_8676web2.jpg"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Black forest",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": [
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            },
            {
               
                "image": "https://d3ugyf2ht6aenh.cloudfront.net/stores/413/750/products/20180907_1624111-7685d28fa6e00dd7f015367770615377-640-0.jpg"
            },
            {
               
                "image": "https://s1.eestatic.com/2019/10/10/cocinillas/recetas/postres/postres_435717801_134838292_1706x960.jpg"
            }
        ],
        "description": "Moist Chocolate Cake, whipped cream, chocolate cream and red berries.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Black Cookies",
        "price": 700,
        "dimension": 5,
        "available": true,
        "type": "none",
        "category": "cookies",
        "image": [
            {
               
                "image": "https://simplelivingrecipes.com/wp-content/uploads/2022/03/fudgy-chocolate-cookies-with-cocoa-powder-s.jpg"
            },
            {
               
                "image": "https://i.blogs.es/80c2c8/galletas-cookies-chocolate/840_560.jpg"
            },
            {
               
                "image": "https://www.sweetestmenu.com/wp-content/uploads/2020/04/chocolatecookies12a.jpg"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Chocolate Cookies",
        "price": 650,
        "dimension": 5,
        "available": true,
        "type": "celiac",
        "category": "cookies",
        "image": [
            {
               
                "image": "https://recetasdecocina.elmundo.es/wp-content/uploads/2015/09/cookies-receta.jpg"
            },
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0UA3HyIV8R_jYrw4_fyBb4p-iY81OCde9nw&usqp=CAU"
            },
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGcQGY3CHADrs5dMlhtr0dtdmz968Fd-8BzQ&usqp=CAU"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Fun Cookies",
        "price": 900,
        "dimension": 5,
        "available": true,
        "type": "vegan",
        "category": "cookies",
        "image": [
            {
               
                "image": "https://i2.wp.com/smittenkitchen.com/wp-content/uploads//2016/05/confetti-cookies1.jpg?fit=1200%2C800&ssl=1"
            },
            {
               
                "image": "https://celebratingsweets.com/wp-content/uploads/2013/08/Sprinkle-Cookies-3.jpg"
            },
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKoYx_qLSlpGbvVlcXwWVkE0VjyKLrkLqjRw&usqp=CAU"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Christmas Cookies",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan_celiac",
        "category": "cookies",
        "image": [
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqVifX15AZWfFgAS7Hg_fj-QAibbEHPzeqPQ&usqp=CAU"
            },
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrkJEGDMg4jlQlf0EQ2tnoYBtp9OgGZ_BFiQ&usqp=CAU"
            },
            {
               
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx2ymJuZUpDSh58mTcN7GLiW4bnb0IscC6_M2m0wSq4POtY_IkbT5x5v5sriSk9i0UPEQ&usqp=CAU"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    },
    {
        "name": "Pepa cookies",
        "price": 7780,
        "dimension": 30,
        "available": true,
        "type": "vegan",
        "category": "cookies",
        "image": [
            {
               
                "image": "https://img-global.cpcdn.com/recipes/18fa4a17da40b644/400x400cq70/photo.jpg"
            },
            {
               
                "image": "https://img-global.cpcdn.com/recipes/18fa4a17da40b644/400x400cq70/photo.jpg"
            },
            {
               
                "image": "https://www.petitchef.es/imgupl/recipe/galletas-pepas--md-17877p22242.jpg"
            }
        ],
        "description": "Rich combination of ground biscuits, with a smooth sweet cream, with hints of lemon and a rich Italian meringue on top.",
        "evaluation": {
            "create": []
        }
    }
]

