/* eslint-disable @next/next/no-page-custom-font */
import React from "react";
import Head from "next/head";

const HEAD = () => (
  <Head>
    <title>Sirun Pâtisserie</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />

    <link
      href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Inter:wght@300;400;700&family=Karla:wght@300;400;700&display=swap"
      rel="stylesheet"
    ></link>
  </Head>
);

export default HEAD;
