
### ////////// others muffins cookies bakery  desserts cakes bakery
##             Otras magdalenas galletas panadería postres pasteles panadería

###
GET http://localhost:3000/api/test/check-image
###




POST http://localhost:3000/api/adminScope/post/productPostAdm
Content-Type: application/json

    {
        "name": "SPANISH SPONGE CAKE",
        "price": 500,
        "dimension": 3,
        "available": true,
        "type": "none",
        "category": "desserts",
        "image": [
            {
                "id":"asdad",
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg"
            },
            {
                "id":"sdaa",
                "image": "https://izzycooking.com/wp-content/uploads/2021/05/Spanish-Sponge-Cake-683x1024.jpg"
            },
            {
                "image": "https://tastesbetterfromscratch.com/wp-content/uploads/2017/04/Tres-Leches-Cake-1-1.jpg"
            }
        ],
        "description": "This classic recipe uses four basic ingredients. The lemon zest adds an extra touch of flavor.",
        "evaluation": {
            "create": []
        }
    }