

### USER DETAIL
GET http://localhost:3000/api/userScope/get/ezequiel.ignacio.sosa@gmail.com
###

### FAVORITE PRODUCT
POST http://localhost:3000/api/userScope/post/productAddFav
Content-Type: application/json

{
    "idUser":"7be88830-6282-4c1a-aebc-1353eefdf3be", 
    "idProduct":"8bcca193-7380-4c68-bdd2-9ea5eafcf6a6" 
}
###

###REVIEW ADD RATING
POST http://localhost:3000/api/userScope/post/reviewRating
Content-Type: application/json

{
    "idUser":"f4690285-1572-447c-b9ad-de26c3672e3b", 
    "idProduct":"2539ccfe-60ef-4ba3-b22c-cd3d32139dad",
    "review":"ESTA MALISIMA",
    "rating":1
}
###

###ORDER
POST http://localhost:3000/
####
POST http://localhost:3000/api/reviews/2539ccfe-60ef-4ba3-b22c-cd3d32139dad

###
Content-Type: application/json

{
    "idUser":"c7617145-1376-4ef9-8cf0-74ba99f7fbc6", 
    "idArrayProduct":[{
            "id":"05d97afa-bc17-4838-8ae5-d27d46e18530"
            },        {
            "id":"0cd6c821-334e-4202-80e1-ea46eab13fb0"
            },        {
            "id":"14c4096a-4f19-4481-985e-dbc705f8fb01"
            },{
            "id":"2bfa1911-0769-4136-b6c3-efa94c2eac0a"
            },{
            "id":"37106465-a3ad-4dbf-9796-1e3ce9eb3015"
            }],
    "description":"VaMOSSSSSSS",
    "status":"pending",
    "delivery_time":"4 dias aprox" 
}
###

####
POST http://localhost:3000/api/reviews/2539ccfe-60ef-4ba3-b22c-cd3d32139dad

###


####
DELETE  http://localhost:3000/api/userScope/delete/54a717a4-53fb-4833-b64b-ff5688b534f4

###

###