

POST http://localhost:3000/api/test/sembradoAux
Content-Type: application/json

[ 
  {
    "id": "6bb75394-de30-40b1-9bc4-ac00e932f1f3",
    "name": "Best bread in town",
    "price": 500,
    "dimension": 50,
    "available": true,
    "type": "celiac",
    "category": "bakery",
    "description": "Best bread in town sold as in pictures.",
    "image": [
      {
        "id": "bxqf1mzsbvwcjp5nlura",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884508/products/bxqf1mzsbvwcjp5nlura.jpg"

      },
      {
        "id": "xcae6tkjqj3mjn01ox4b",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884497/products/xcae6tkjqj3mjn01ox4b.jpg"
        
      },
      {
        "id": "exeb3kp2c8zaqtccwhiy",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884495/products/exeb3kp2c8zaqtccwhiy.jpg"
        
      }
    ]
  },
  {
    "id": "7e4930b8-9d1c-4603-80a5-ac916490f236",
    "name": "Pack Ferrero muffins",
    "price": 1750,
    "dimension": 7,
    "available": true,
    "type": "none",
    "category": "muffins",
    "description": "The pack includes 6 Ferrero muffins with Ferrero filling and hazelnuts topping.",
    "image": [
      {
        "id": "ixm9i1vva0witu9ch4xb",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881650/products/ixm9i1vva0witu9ch4xb.jpg"
        
      },
      {
        "id": "fa2yugmxc0eut3y7ybok",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881647/products/fa2yugmxc0eut3y7ybok.jpg"
        
      },
      {
        "id": "iu1mqusrpqjv8uaso9rq",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881647/products/iu1mqusrpqjv8uaso9rq.jpg"
        
      },
      {
        "id": "rw6f8qi3376sqmb6435m",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881650/products/rw6f8qi3376sqmb6435m.jpg"
        
      }
    ]
  },
  {
    "id": "6dba19f3-e144-465b-920c-3ad6a4ebba26",
    "name": "Pack carrot muffins",
    "price": 1650,
    "dimension": 7,
    "available": true,
    "type": "none",
    "category": "muffins",
    "description": "The pack includes 6 carrot muffins with creamy carrot and vanilla filling and vanilla cover and almond topping.",
    "image": [
      {
        "id": "r20ttooxpfhxs1orj9np",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882293/products/r20ttooxpfhxs1orj9np.jpg"
        
      },
      {
        "id": "onzvifg3p9jvlrypjwcy",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882292/products/onzvifg3p9jvlrypjwcy.jpg"
        
      },
      {
        "id": "wtxfwhdppxtsapauem0t",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882292/products/wtxfwhdppxtsapauem0t.jpg"
        
      },
      {
        "id": "faskcnypvqtgw3gxei2r",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882292/products/faskcnypvqtgw3gxei2r.jpg"
        
      }
    ]
  },
  {
    "id": "d984649c-06a1-4cc5-8d9e-2dea07e9e7ec",
    "name": "Pack Oreo muffins",
    "price": 1750,
    "dimension": 7,
    "available": true,
    "type": "vegan",
    "category": "muffins",
    "description": "The pack includes 6 vegan Oreo muffins with vanilla and Oreo filling and vanilla cover with Oreo topping.",
    "image": [
      {
        "id": "xwg9ansbyg46zw4sen1g",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882837/products/xwg9ansbyg46zw4sen1g.jpg"
        
      },
      {
        "id": "nryreflxm12nyhdkz1dp",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882837/products/nryreflxm12nyhdkz1dp.jpg"
        
      },
      {
        "id": "ydw0q9nhwjvzn1mzxwbw",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669882838/products/ydw0q9nhwjvzn1mzxwbw.jpg"
        
      }
    ]
  },
  {
    "id": "c0516444-a925-48d3-b3a4-fd4fb29d8a63",
    "name": "Pack strawberry muffins",
    "price": 1600,
    "dimension": 7,
    "available": true,
    "type": "none",
    "category": "muffins",
    "description": "The pack includes 6 strawberry muffins with vanilla and strawberry filling and merengue-strawberry topping.",
    "image": [
      {
        "id": "j5umt0osqvbq1whziuqo",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881767/products/j5umt0osqvbq1whziuqo.jpg"
        
      },
      {
        "id": "f4w3ferrjzwvu0imvvvf",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881767/products/f4w3ferrjzwvu0imvvvf.jpg"
        
      },
      {
        "id": "fkqvupzsode8iqgwec1u",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881767/products/fkqvupzsode8iqgwec1u.jpg"
        
      },
      {
        "id": "kut0af6homdugjrfh6la",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881767/products/kut0af6homdugjrfh6la.jpg"
        
      }
    ]
  },
  {
    "id": "066ec9be-a198-48be-bccd-e0ba8d1ae19c",
    "name": "Pack vanilla muffins",
    "price": 1600,
    "dimension": 7,
    "available": true,
    "type": "none",
    "category": "muffins",
    "description": "The pack includes 6 vanilla muffins with vanilla filling and vanilla-merengue topping.",
    "image": [
      {
        "id": "tz1lcdzmfq7pb48bb6g6",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881862/products/tz1lcdzmfq7pb48bb6g6.jpg"
       
      },
      {
        "id": "drinyeuwuhgfmvlg1nir",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881860/products/drinyeuwuhgfmvlg1nir.jpg"
       
      },
      {
        "id": "ojwmo6wk2nqa2pydkpdy",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669881862/products/ojwmo6wk2nqa2pydkpdy.jpg"
       
      }
    ]
  },
  {
    "id": "3da54b3c-b08e-4695-9553-743627ee188b",
    "name": "Ricotta and lemon cake",
    "price": 2450,
    "dimension": 40,
    "available": true,
    "type": "celiac",
    "category": "cakes",
    "description": "Irresistible ricotta and lemon cake with creamy vanilla ricotta filling and lemon topping and crunchy bottom.",
    "image": [
      {
        "id": "nwph2dymkaxbivu3e98l",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883321/products/nwph2dymkaxbivu3e98l.jpg"
        
      },
      {
        "id": "dbbdrxrwcct6ifltpxva",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883321/products/dbbdrxrwcct6ifltpxva.jpg"
        
      },
      {
        "id": "vwoqaei3rjqiwi8bdgb0",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883321/products/vwoqaei3rjqiwi8bdgb0.jpg"
        
      }
    ]
  },
  {
    "id": "df2a60f6-c793-42d2-a3ac-c62f627d582c",
    "name": "Lemon cake",
    "price": 2630,
    "dimension": 30,
    "available": true,
    "type": "none",
    "category": "others",
    "description": "Soft high lemon cake that can be decorated as you like (check product pictures). Lemon and vanilla creamy filling with vanilla mousse and lemon glace top.",
    "image": [
      {
        "id": "nnqzqidp5yjidtcs3igf",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883563/products/nnqzqidp5yjidtcs3igf.jpg"
        
      },
      {
        "id": "grrksklzaj6tyfcpcdy6",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883563/products/grrksklzaj6tyfcpcdy6.jpg"
        
      },
      {
        "id": "hhbmympbewbsnhhe9lgf",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883563/products/hhbmympbewbsnhhe9lgf.jpg"
        
      },
      {
        "id": "n8hn3afwvfxum5dojhcv",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883563/products/n8hn3afwvfxum5dojhcv.jpg"
        
      }
    ]
  },
  {
    "id": "b813b6a1-babf-4076-9185-348de1ed1482",
    "name": "Bruce cake from Matilda movie",
    "price": 2670,
    "dimension": 30,
    "available": true,
    "type": "none",
    "category": "cakes",
    "description": "Chocolate mousse with chocolate filling, humid chocolate cover and chocolate topping have made it possible to recreate the famous cake from the Matilda movie.",
    "image": [
      {
        "id": "yydxl2iddsr3qq0qvml2",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883930/products/yydxl2iddsr3qq0qvml2.jpg"
        
      },
      {
        "id": "t3soin216vtnk1xmljuw",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883930/products/t3soin216vtnk1xmljuw.jpg"
        
      },
      {
        "id": "voxzankkrvcmg8a6ozls",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883930/products/voxzankkrvcmg8a6ozls.jpg"
        
      },
      {
        "id": "ud5fk4zystxppthgux1m",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669883929/products/ud5fk4zystxppthgux1m.jpg"
        
      }
    ]
  },
  {
    "id": "47405340-272e-4944-81e6-df1dc08f3bbc",
    "name": "Frozen caramel cake",
    "price": 2500,
    "dimension": 30,
    "available": true,
    "type": "none",
    "category": "cakes",
    "description": "Frozen creamy caramel cake with vanilla mousse, vanilla and caramel interior, frozen chocolate cover and creamy hazelnut and honey topping. You can decorated as you like (check product pictures).",
    "image": [
      {
        "id": "jbuq1wp3hh9hxicxoh84",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884259/products/jbuq1wp3hh9hxicxoh84.jpg"
        
      },
      {
        "id": "jlsbyiyqg6wab80hmao0",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884259/products/jlsbyiyqg6wab80hmao0.jpg"
        
      },
      {
        "id": "d9xp7y2jzgyaib13xbzz",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884260/products/d9xp7y2jzgyaib13xbzz.jpg"
        
      },
      {
        "id": "gnaioqa9kw0wmbj1rmg4",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884260/products/gnaioqa9kw0wmbj1rmg4.jpg"
        
      }
    ]
  },
  {
    "id": "34495add-31c4-4baa-aaa0-afda8360c9b9",
    "name": "Pack chocolate chip cookies",
    "price": 1200,
    "dimension": 9,
    "available": true,
    "type": "none",
    "category": "cookies",
    "description": "The pack includes 6 chocolate chip cookies with Nutella interior.",
    "image": [
      {
        "id": "d8lhwqjgzg01wshvshlx",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884745/products/d8lhwqjgzg01wshvshlx.jpg"
       
      },
      {
        "id": "u9mz1x2sz5eeea4zuvwd",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884747/products/u9mz1x2sz5eeea4zuvwd.jpg"
       
      },
      {
        "id": "x9pbq8ag5qrkxueppj56",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884744/products/x9pbq8ag5qrkxueppj56.jpg"
       
      },
      {
        "id": "edc5phfyawaqlzq5zdu5",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884745/products/edc5phfyawaqlzq5zdu5.jpg"
       
      }
    ]
  },
  {
    "id": "b929567f-7b9c-4fec-8ce0-5f6e8df39fb4",
    "name": "Pack Nutella muffins",
    "price": 1750,
    "dimension": 6,
    "available": true,
    "type": "none",
    "category": "muffins",
    "description": "The pack includes 6 Nutella muffins with Nutella filling, Nutella and vanilla mousse and Nutella cover.",
    "image": [
      {
        "id": "geax6prajrykkdftcllu",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884894/products/geax6prajrykkdftcllu.jpg"
       
      },
      {
        "id": "vrzqfedcgap8k3v5gcfk",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884892/products/vrzqfedcgap8k3v5gcfk.jpg"
       
      },
      {
        "id": "fece559ynllpvs3uwawu",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884893/products/fece559ynllpvs3uwawu.jpg"
       
      },
      {
        "id": "eluixlggq7lvmzqhshyx",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669884892/products/eluixlggq7lvmzqhshyx.jpg"
       
      }
    ]
  },
  {
    "id": "99cc1924-c106-46e7-ac0a-ea93d6325ac1",
    "name": "Pack Oreo balls",
    "price": 3000,
    "dimension": 8,
    "available": true,
    "type": "none",
    "category": "desserts",
    "description": "The pack includes 6 Oreo balls with truffle filling, hard vanilla cover and Oreo topping.",
    "image": [
      {
        "id": "sedlcwt9uzq3y22fxvnn",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886289/products/sedlcwt9uzq3y22fxvnn.jpg"
       
      },
      {
        "id": "top7akrffimxgf4tmv8y",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886289/products/top7akrffimxgf4tmv8y.jpg"
       
      },
      {
        "id": "f0aao8hrexig9impdedb",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886289/products/f0aao8hrexig9impdedb.jpg"
       
      },
      {
        "id": "dhkitffjn7nx6oq3zyke",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886290/products/dhkitffjn7nx6oq3zyke.png"
       
      }
    ]
  },
  {
    "id": "8c9c4e9b-d200-47fc-9e72-6692a99ac744",
    "name": "Pack chocolate truffles",
    "price": 1700,
    "dimension": 4,
    "available": true,
    "type": "none",
    "category": "desserts",
    "description": "The pack includes 10 dark chocolate truffles. Toppings can vary between: grated coconut, shredded chocolate, almonds flakes, hazelnut flakes or anything you want!",
    "image": [
      {
        "id": "eibqetivy9nw6sncoluw",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886601/products/eibqetivy9nw6sncoluw.jpg"
       
      },
      {
        "id": "k866t0jofafq9xrzuwwi",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886601/products/k866t0jofafq9xrzuwwi.jpg"
       
      },
      {
        "id": "mce1l22zv3orswztluqj",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886601/products/mce1l22zv3orswztluqj.jpg"
       
      },
      {
        "id": "j5ot8rhc9ezyrb71zgzg",
        "image": "https://res.cloudinary.com/dvopyvz7r/image/upload/v1669886601/products/j5ot8rhc9ezyrb71zgzg.jpg"
       
      }
    ]
  }

]