###
GET  http://localhost:3000/api/product/gets/detailById/360c3542-3a30-4bdc-9e5c-a6e161d29cc4
###




POST http://localhost:3000/api/test/manyProduc
Content-Type: application/json

[
    {     
        "name": "Torta Corazon de Cumpleaños",
        "price": 7000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEVJbNFrw9ACs985DbBV58ZOmiw2hRKHZb5N7MTDXcpHchHMlut6EC2dlHuecS4q4DSMVzU8mL2Qrit5LW5r_tid15d5Mcb_NqCie4PPiq2Rh-Lst4LgOdjLyRxj7QBp9h3L2iLJmEkyCoSrsh1rq2oi=w713-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEW995nujco9nAMhopqSkGQohOTUnt1mlRM3zTT_eBEdirn6Qv4Da1yUcVj5A3JZV6ZMjRKZZwlJUvv4oCQqEzeaFsoGR-2sXGTceTO9hl6hUhmi1ry5Oc_481jkM35UiLo617bMDpv5vJreXNBoJ8JK=w713-h950-no?authuser=1"],
        "description" : "Torta para 24 porciones. Relleno a eleccion. Decoracion con crema chantilly. ESTE PRODUCTO REQUIERE MINIMO 72 HS. DE ELABORACION "
    },
    {     
        "name": "Torta de Bodas",
        "price": 9000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEUg00eC-5yZZSmZX6RWpkRiLOhRy2YaDENL6jg8td_SHLu3cIRP9a_cpC_Vk61nuKCY3RSX7WG38HYQUopEKj3tgFxV29QjAsF0WdzqaIe9WViS11wDiKKmBPlT_YD2zfl4LWoOioGXDZt9SVzjwOLi=w769-h950-no?authuser=1"],
        "description" : "Drip cake de dos pisos con butter cream. ESTE PRODUCTO REQUIERE 72 HS. DE ELABORACION"
    },
    {     
        "name": "Torta de Bautismo/Nacimiento",
        "price": 8000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEU4gS6fTO4EcuOVivk1_wFMSP2exGBH719OKzl0gkHnkVCvHc9RhYEreF_hKFfh-7i-op6YAX8FSQAz8noUorR8HAYG89UWdtvHUDWYvt41X4oAvXc3rR7Gd12pOuX7B-8gOHqpx15VSTc6dT6Hsf4_=w713-h950-no?authuser=1"],
        "description" : "Torta para 24 porciones. Relleno y Decoracion a eleccion. ESTE PRODUCTO REQUIERE MINIMO 72 HS. DE ELABORACION"
    },
    {     
        "name": "Torta Brownie",
        "price": 7000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEVj0cqo73xvZPg_eL4vEvyqilWl_-dfzsVLgf412iPqBjhHqosri-PbY9kseIgvPgG2vSIYIJbBZuYdJl-EHBnP7kQ6PqPPojWB2a5FV7iVw1bAeW9N3ZANYNfGeCulccx43y29zEkvKA0QqCuDPxcu=w713-h950-no?authuser=1"],
        "description" : "Brownie, dulce de leche y merengue italiano. ESTE PRODUCTO REQUIERE 72 HS. DE ELABORACION"
    },
    {     
        "name": "Rogel",
        "price": 7300,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://www.madapatisserie.com/fotos/prods/1626266692.jpg"],
        "description" : "Clásica torta Argentina,  finas capas crocantes y dulce de leche, decorada con merengue italiano. ESTE PRODUCTO TIENE 72 HS. DE ELABORACION."
    },
    {     
        "name": "ChocoTorta",
        "price": 7300,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://www.madapatisserie.com/fotos/prods/1596672168.jpg"],
        "description" : "Clasica torta de chocolinas y crema de dulce de leche cubierta con rulos de chocolate.ESTE PRODUCTO REQUIERE 72 HS DE ELABORACION"
    },
    {     
        "name": "Lemon Pie",
        "price": 7000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://www.madapatisserie.com/fotos/prods/1626266826.jpg"],
        "description" : "Fina masa sable, curd de limon y merengue italiano. ESTE PRODUCTO REQUIERE 72 HS. DE ELABORACION"
    },
    {     
        "name": "Cheesecake",
        "price": 7300,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://www.madapatisserie.com/fotos/prods/1646529520.jpg",
        "https://images.unsplash.com/photo-1565467988204-44fc3fd3c726?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
        "https://images.unsplash.com/photo-1565605926614-8b9928ef9b03?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"],
        "description" : "Clasico cheesecake con frutos rojos. ESTE PRODUCTO REQUIERE 72 HS ELABORACION"
    },
    {     
        "name": "Unicorn Cake",
        "price": 8000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEUDQqQQUHTuz4SWD8pIQB7P-2AVVkpkfnKEbtrYslQ6PdO36oJsfLr1Un8TLB7KPalt8oZES2eq8e8kUoeXBaKg-w3GjJWsCZsDsKiqvDlchTPfq_y6J7D1BT3n9f58W3HF57TD_Mu7oztduDKYVK0R=w760-h950-no?authuser=1"],
        "description" : "Torta Unicornio. Relleno y bizcochuelo a eleccion.  ESTE PRODUCTO SE PIDE CON 15/20 DIAS DE ANTICIPACION "
    },
    {     
        "name": "Torta de Cumpleaños",
        "price": 8500,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXR_tbzmDCOB-ugfcNUeVclhwxURaNIcPS1KlWXtsGTTX_Lo-k7p-xu-kVTJWcihHpWkJwVOXmL8uSeSFevLzJxhtRrMoa_qf1t2YSIOoLKs4QSFIphzusfFl-uEFxgs6yymj0XJu9cZr26PA4TZKSw=w713-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEVn85zh-1BNfrf1DaJI9-XmRUgM2QhLkK9hFtk5uNpwzsGLwmUBJJbiGWVVruVAYKYtAdPiBeQUtCDNrwrL6ns7Z1DRHzAkeFRo5hrsfAggMlZKCUIVVo0XL_iJ7AJW6qMWBU95r-8kTEaAUY4J8dHl=w713-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEXgtU7232bpYw9hp0dQ9NOocjdOV2useKBcx1R7dRhp2dnJ41kbfY_Vb_Qnr1Aq84esex84uOKM6M57BP_YYuI9MxP1tQns_DqPF-m1zrfyCGxTtSgjwTxlTefwSSCrRsobK9Gsm3A2_FPhu_Fq-MT9=w713-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEVMkiUm5s2I1WEQIwbAO0u9ubsCrvJvaBMew1NqMPvZYV6zR5G8sGxJ_rzT53RBjhDQSSdkKri_Ulr48i28LhiEdAddBBb9ejfcYMWnhx9pwUFnDq-DG0vNla2ubihq6ifjoyRiluGziMYcY6SoTIih=w713-h950-no?authuser=1"],
        "description" : "Torta de Cumpleaños. Relleno y bizcochuelo a eleccion.  ESTE PRODUCTO REQUIERE 72 HS ELABORACION"
    },
    {     
        "name": "Torta de Cumpleaños Infantil",
        "price": 9000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0",
        "https://lh3.googleusercontent.com/pw/AL9nZEXMAyi-PSqeOnCR-bYv0wHTzgj8b11EKwRMNlauSmaTeqnm3bIAo-pt935IluVnQ67mg93CJG8z34uRo4zJ3ljnpkA8CpsO0RrmVKN5DXiaZYUD8xaqYXTSEshgqY02PWRu06aJHaWtNF6Uu7g4XHNR=w694-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEUVzPijQQjB-KggorXhohssBF6Evcn9KxyGtnxQSt6ukGog4431Wr0atxFqE8u9Ny2iee51PKZqVODP7PyGcXsae-T5oiDs3rt0gAx6HmREHNkh2HPIKF6zCpSuGRFOq_ty8o2kr5LaF5LOFVdtfXEW=w713-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEV9HWOPF-TYOdtknfbAqYAs6uTTrvtwY4qnS_28w_-x8pf9kna8wJQQuEuO6uD18U7JLlQhfJsuRv41FNOwvdo6w3gvCk_ggxcMhE9ke2iytaJirD7-xJlapg_ru7oCEC160hA0d2VTaePqcHtN15RH=w678-h950-no?authuser=1",
        "https://lh3.googleusercontent.com/pw/AL9nZEU__z3n_pxnGsltRYgWLx7hcK6883wSV0qVIBPgowZdKrEtnPXfP4E_0BzbtmGEkFuA5r6rzU3aSJnp5mO1Wu6n0SWqvVYee5FuCx3EBKJSG_fgsZHilq3xLixbvINH7ZDz07Wwi3znvtWKc1XLtLx7=w713-h950-no?authuser=1"],
        "description" : "Torta de Cumpleaños Infaltil para 24 porciones. Decoracion segun la tematica elegida. Relleno y bizcochuelo de vainilla o chocolate. Opciones: relleno crema de avellanas, crema y frutillas.  ESTE PRODUCTO SE PIDE CON 15/20 DIAS DE ANTICIPACION"
    },
    {     
        "name": "Torta de Frutillas",
        "price": 8000,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0"],
        "description" : "Clasico bizcochuelo de vainilla relleno con crema y frutillas.  ESTE PRODUCTO REQUIERE 72 HS ELABORACION "
    },
    {     
        "name": "Torta de Nutella",
        "price": 8500,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0"],
        "description" : "Torta con relleno y cobertura de nutella. Bizcochuelo de chocolate.  ESTE PRODUCTO REQUIERE 72 HS ELABORACION"
    },
    {     
        "name": "",
        "price": 999,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0"],
        "description" : "nshshshsh sshhshs shshsh hahaha ahahaha ahaha"
    },
    {     
        "name": "TORTA14",
        "price": 999,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0"],
        "description" : "nshshshsh sshhshs shshsh hahaha ahahaha ahaha"
    },
    {     
        "name": "TORTA14",
        "price": 999,     
        "dimension": 30,      
        "available": true,
        "type": "vegan",
        "category": "cakes",
        "image": ["https://lh3.googleusercontent.com/pw/AL9nZEXsx7U4m1Ojrw-f51ojXodreVQY4zsBse1LWljIsiTh34-kFyl_f86B7auYUCbMHVKVDaAfG1NPNLel6K5knb7LjJ3EPljcos3QuJZhumZenWj1UcVd19NAGlZ6EWVNAN9SBtkQrO8t8T4DjwjCNyTklw=w477-h636-no?authuser=0"],
        "description" : "nshshshsh sshhshs shshsh hahaha ahahaha ahaha"
    }
]
